# Generated by Django 4.0.6 on 2022-07-12 19:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.IntegerField(default=0)),
                ('nombre', models.CharField(max_length=100)),
                ('modificado', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Envase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(default=0)),
                ('cantidad', models.IntegerField(default=0)),
                ('modificado', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.IntegerField(default=0)),
                ('nombre', models.CharField(max_length=100)),
                ('modificado', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('modificado', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tienda.cliente')),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tienda.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField(default=0)),
                ('nombre', models.TextField()),
                ('modificado', models.DateTimeField(default=django.utils.timezone.now)),
                ('envase', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tienda.envase')),
                ('medida', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tienda.medida')),
            ],
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('modificado', models.DateTimeField(default=django.utils.timezone.now)),
                ('producto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
                ('unidad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tienda.unidad')),
            ],
        ),
    ]
