# Generated by Django 4.0.6 on 2022-07-13 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_venta_total_alter_venta_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cod',
            field=models.IntegerField(default=0, max_length=16),
        ),
    ]
