# Generated by Django 4.0.6 on 2022-07-13 00:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_producto_cod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medida',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='medida',
            name='tipo',
        ),
        migrations.AddField(
            model_name='envase',
            name='modificado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='medida',
            name='nombre',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unidad',
            name='modificado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='envase',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cod',
            field=models.CharField(max_length=30),
        ),
    ]
