# Generated by Django 4.0.6 on 2022-08-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_unidad_unidades_alter_cliente_ci_alter_usuario_ci'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='total',
            new_name='efectivo',
        ),
        migrations.RemoveField(
            model_name='unidad',
            name='cod',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='precio',
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='peso',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venta',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
