# Generated by Django 4.0.6 on 2022-08-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_rename_total_venta_efectivo_remove_unidad_cod_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precio',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='precio',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='precio',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
