# Generated by Django 4.0.6 on 2022-08-07 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_empresa_alter_producto_nombre_producto_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='envase',
        ),
    ]
