# Generated by Django 4.0.6 on 2022-08-07 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_remove_producto_envase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='empresa',
        ),
        migrations.AddField(
            model_name='producto',
            name='envase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tienda.envase'),
        ),
    ]
