# Generated by Django 4.0.6 on 2022-08-07 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_remove_producto_empresa_producto_envase'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.empresa'),
        ),
    ]
