# Generated by Django 4.0.6 on 2022-08-07 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_producto_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='envase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.envase'),
        ),
    ]
