# Generated by Django 4.0.6 on 2022-08-07 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_alter_producto_envase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.medida'),
        ),
    ]
