# Generated by Django 4.0.6 on 2022-08-08 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0013_alter_producto_medida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidad',
            name='unidades',
        ),
    ]
