# Generated by Django 4.0.6 on 2022-08-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0014_remove_unidad_unidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
