# Generated by Django 4.0.6 on 2022-08-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0016_alter_producto_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='volumen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='producto',
            name='peso',
            field=models.IntegerField(default=0),
        ),
    ]
